{% set name = "PyKrige" %}
{% set version = "1.7.0" %}
{% set sha256 = "c814b65f00f55b2ede79b52132985a2a0015b8b397341938e27ed53a24bc63de" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - scipy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - toml
    - setuptools >=62
    - setuptools_scm >=6.4
    - cython >=0.28.3, <3.0
    - numpy
    - scipy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}

test:
  imports:
    - pykrige
  requires:
    - pytest >=5.3.0
    - scikit-learn >=0.19
    - gstools >=1.4.0, <2.0
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/GeoStat-Framework/PyKrige
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Kriging Toolkit for Python
  description: |
    The code supports two- and three- dimensional ordinary and universal
    kriging. Standard variogram models (linear, power, spherical,
    gaussian, exponential) are built in, but custom variogram models
    can also be used with the code.
  doc_url: http://pykrige.readthedocs.io/
  dev_url: https://github.com/GeoStat-Framework/PyKrige

extra:
  recipe-maintainers:
    - rth
    - MuellerSeb
