{% set name = "PyKrige" %}
{% set version = "1.4.0" %}
{% set sha256 = "63f4c93e20fa94bedc41853322feb924c9289b382ddc5678120ddb25777cdfbe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 1002
  script: python -m pip install --no-deps --ignore-installed .  --verbose

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
    - cython
    - numpy
    # we use scipy BLAS in Cython
    - scipy
    - matplotlib-base >=1.4.3
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}
    - matplotlib-base >=1.4.3


test:
  imports:
    - pykrige

about:
  home: https://github.com/bsmurphy/PyKrige
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: LICENSE.txt
  summary: 'Kriging Toolkit for Python'
  description: |
      The code supports two- and three- dimensional ordinary and universal
      kriging. Standard variogram models (linear, power, spherical,
      gaussian, exponential) are built in, but custom variogram models
      can also be used with the code.

  doc_url: http://pykrige.readthedocs.io/en/latest/
  dev_url: https://github.com/bsmurphy/PyKrige

extra:
  recipe-maintainers:
    - rth
